# Generated by Django 5.0.7 on 2024-08-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalauth', '0002_doctor_patient_medicalrecord_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaluser',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hospitaluser',
            name='is_patient',
            field=models.BooleanField(default=False),
        ),
    ]
